// Code generated by coz. DO NOT EDIT.
/**
 * Component to show caught errors
 * @module the-caught
 */
'use strict'

import TheCaught from './TheCaught'
import TheCaughtStyle from './TheCaughtStyle'

export {
 TheCaught,
 TheCaughtStyle,
}
